steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/revid-api:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/revid-api:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'revid-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/revid-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'API_KEY=$$API_KEY,OPEN_AI_API_KEY=$$OPEN_AI_API_KEY,MUSIC_MS_TOKEN=$$MUSIC_MS_TOKEN'

# Store image in Artifact Registry
images:
  - 'gcr.io/$PROJECT_ID/revid-api:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY